### ISSUE TITLE
403 when trying to access https://genodians.org/

### ISSUE THREAD

**Issue by mewmew** [nfeske/genodian#1]
Hej Genodians!

I'm really excited to start reading f90ee8897444ad6235ae6fb2b9b194dca8652955. As I try to access https://genodians.org/ today (which resolves to 94.130.141.202 on my machine), I get a 403 Forbidden error.

Perhaps this is a known issue?

![screenshot_2022-05-04_12:12:31](https://user-images.githubusercontent.com/1414531/166662367-47d3cb43-b92a-4188-ae16-f91cecbd35f7.png)

Cheerful summer greetings from Sweden,
Robin

**Edit:** perhaps this issue would have been better suited for https://github.com/genodelabs/genodians.org/issues?

**Comment by nfeske** [comment]
Thanks Robin for the report. Yes, we noticed the problem and are working on it. :) Stay tuned.

**Comment by nfeske** [comment]
Genodians.org should work again now. The problem was actually quite surprising (https://github.com/genodelabs/genodians.org/commit/5564e943a1dd2126bc7fdcf8fb0cc58bc0f54b3e). Thanks to @skalk and @chelmuth for investigating!

**Comment by mewmew** [comment]
Great, it works! And https://genodians.org/nfeske/2022-05-03-pine-fun-trimming-drivers is out :) Diving in to read.

Cheers,
Robin

**Edit:** feel free to re-open this issue, or open a new dedicated one to track the root cause to which [5564e943a1dd2126bc7fdcf8fb0cc58bc0f54b3e](https://github.com/genodelabs/genodians.org/commit/5564e943a1dd2126bc7fdcf8fb0cc58bc0f54b3e) is a work-around.
